"use client";

import { useTranslation } from "@/lib/i18n";

const vi = {
  reset: "Khôi phục mặc định", preview: "Xem trước thực tế", monochrome: "đơn sắc",
  previewHint: "Bản xem trước dùng dữ liệu mẫu và thay đổi ngay khi chỉnh cấu hình.",
  paperTitle: "Khổ giấy máy in", paperDescription: "Chọn đúng vùng in thực tế của máy in nhiệt.",
  paperNotice: "POS82 cho phép vùng in tối đa 82 mm. Hãy chọn đúng khổ giấy trên máy POS khi in lần đầu.",
  brandTitle: "Nhận diện cửa hàng", brandDescription: "Logo tự chuyển sang thang xám và tăng tương phản khi in.",
  uploadLogo: "Tải logo lên", replaceLogo: "Thay logo", removeLogo: "Xóa logo", logoAlt: "Logo cửa hàng",
  logoInvalid: "Logo không hợp lệ", logoInvalidDescription: "Chỉ chấp nhận ảnh PNG, JPG hoặc WEBP.",
  logoTooLarge: "Logo quá lớn", logoTooLargeDescription: "Vui lòng chọn ảnh nhỏ hơn 600 KB.",
  logoReadError: "Không thể đọc logo", logoReadErrorDescription: "Vui lòng chọn một tệp ảnh khác.",
  logoReady: "Đã cập nhật logo", logoReadyDescription: "Ảnh sẽ được chuyển sang đơn sắc khi in nhiệt.",
  logoWidth: "Chiều rộng logo", logoHeight: "Chiều cao tối đa", logoContrast: "Độ đậm logo",
  themeTitle: "Chủ đề trang trí", themeDescription: "Chủ đề đổi hoa văn và câu chúc; nội dung đơn hàng giữ nguyên.",
  showTheme: "Hiển thị câu chủ đề", showThemeDescription: "Câu chúc được in trong banner trang trí",
  themeText: "Câu chủ đề", themeFontSize: "Cỡ chữ câu chủ đề",
  qrTitle: "QR yêu cầu xuất hóa đơn", qrDescription: "Điều chỉnh mã QR và phần chữ hướng dẫn xuất hóa đơn.",
  showQr: "Hiển thị QR xuất hóa đơn", showQrDescription: "Chỉ xuất hiện khi đơn hàng có đường dẫn hợp lệ",
  qrSize: "Kích thước mã QR", qrTitleSize: "Cỡ chữ tiêu đề", qrHintSize: "Cỡ chữ chú thích",
  fontTitle: "Độ đậm nét in", fontDescription: "Điều chỉnh riêng từng thành phần để máy in nhiệt cho nét ổn định.",
  contentTitle: "Nội dung nâng cao", contentDescription: "Chọn thông tin bổ sung và cách tính thuế cho đơn hàng cũ.",
  showLogo: "Hiển thị logo", showLogoDescription: "Ẩn logo nhưng vẫn giữ tệp đã tải",
  showCashier: "Hiển thị nhân viên", showCashierDescription: "Lấy từ người tạo đơn",
  showItemTax: "Thuế theo từng món", showItemTaxDescription: "In thuế suất và tiền thuế dưới dòng hàng",
  showContact: "Thông tin liên hệ", showContactDescription: "Hotline và nội dung hậu mãi",
  defaultTax: "Thuế mặc định cho đơn cũ", afterSales: "Thông tin hậu mãi", footer: "Lời cảm ơn cuối biên lai",
  storeName: "Tên cửa hàng", address: "Địa chỉ", hotline: "Hotline",
  saveLoading: "Đang lưu cấu hình hóa đơn...", saveSuccess: "Đã lưu cấu hình hóa đơn",
  saveSuccessDescription: "Cấu hình mới đang được gửi tức thì tới các máy JPOS của cửa hàng.",
  saveError: "Không thể lưu cấu hình", saveErrorDescription: "Vui lòng kiểm tra dữ liệu, kết nối mạng rồi thử lại.",
  retry: "Thử lại", receiptTitle: "BIÊN LAI BÁN HÀNG", orderCode: "Mã đơn", dateTime: "Ngày giờ",
  cashier: "Nhân viên", payment: "Thanh toán", goods: "HÀNG HÓA", amount: "THÀNH TIỀN",
  hotlineLabel: "Hotline", cashPayment: "Tiền mặt", sampleTicket: "Vé vui chơi trọn gói",
  sampleGift: "Gấu bông B.Duck mini", itemTax: "Thuế",
  subtotal: "Tạm tính", discount: "Giảm giá", taxTotal: "Tổng tiền thuế", total: "TỔNG TIỀN",
  invoiceQrTitle: "Quét mã để yêu cầu xuất hóa đơn", invoiceQrHint: "Vui lòng điền thông tin xuất hóa đơn trước 22:30 cùng ngày.",
};

const zh: typeof vi = {
  reset: "恢复默认", preview: "实时预览", monochrome: "黑白",
  previewHint: "预览使用示例数据，并会随配置修改即时变化。",
  paperTitle: "打印纸规格", paperDescription: "请选择热敏打印机的实际打印宽度。",
  paperNotice: "POS82 支持最大 82 mm 打印区域，首次打印时请在 POS 上选择正确纸张。",
  brandTitle: "门店标识", brandDescription: "Logo 打印时会自动转为灰度并增强对比度。",
  uploadLogo: "上传 Logo", replaceLogo: "更换 Logo", removeLogo: "删除 Logo", logoAlt: "门店 Logo",
  logoInvalid: "Logo 无效", logoInvalidDescription: "仅支持 PNG、JPG 或 WEBP 图片。",
  logoTooLarge: "Logo 过大", logoTooLargeDescription: "请选择小于 600 KB 的图片。",
  logoReadError: "无法读取 Logo", logoReadErrorDescription: "请选择其他图片文件。",
  logoReady: "Logo 已更新", logoReadyDescription: "热敏打印时图片将转为黑白。",
  logoWidth: "Logo 宽度", logoHeight: "最大高度", logoContrast: "Logo 对比度",
  themeTitle: "装饰主题", themeDescription: "主题会改变装饰与祝福语，不影响订单内容。",
  showTheme: "显示主题文案", showThemeDescription: "祝福语显示在装饰横幅中",
  themeText: "主题文案", themeFontSize: "主题字号",
  qrTitle: "发票申请二维码", qrDescription: "调整二维码与发票申请说明文字。",
  showQr: "显示发票二维码", showQrDescription: "仅在订单有有效申请链接时显示",
  qrSize: "二维码尺寸", qrTitleSize: "标题字号", qrHintSize: "说明字号",
  fontTitle: "打印字重", fontDescription: "分别调整各部分字重，提升热敏打印清晰度。",
  contentTitle: "高级内容", contentDescription: "选择附加信息及旧订单默认税率。",
  showLogo: "显示 Logo", showLogoDescription: "隐藏时仍保留已上传文件",
  showCashier: "显示员工", showCashierDescription: "取自订单创建人",
  showItemTax: "显示单项税额", showItemTaxDescription: "在商品下显示税率与税额",
  showContact: "显示联系信息", showContactDescription: "热线与售后说明",
  defaultTax: "旧订单默认税率", afterSales: "售后说明", footer: "小票底部致谢",
  storeName: "门店名称", address: "地址", hotline: "热线",
  saveLoading: "正在保存小票配置...", saveSuccess: "小票配置已保存",
  saveSuccessDescription: "新配置正在即时发送到该门店的 JPOS 设备。",
  saveError: "无法保存配置", saveErrorDescription: "请检查数据和网络连接后重试。",
  retry: "重试", receiptTitle: "销售小票", orderCode: "订单号", dateTime: "时间",
  cashier: "员工", payment: "支付方式", goods: "商品", amount: "金额",
  hotlineLabel: "热线", cashPayment: "现金", sampleTicket: "畅玩套票",
  sampleGift: "B.Duck 迷你毛绒玩具", itemTax: "税额",
  subtotal: "小计", discount: "优惠", taxTotal: "税额合计", total: "应付总额",
  invoiceQrTitle: "扫码申请发票", invoiceQrHint: "发票信息请于当天 22:00 前提交。",
};

export function usePosReceiptEditorCopy() {
  const { lang } = useTranslation();
  return { copy: lang === "zh" ? zh : vi, lang } as const;
}
