"use client";

import { useTranslation } from "@/lib/i18n";

const vi = {
  tab: "Đơn hàng",
  title: "Đơn hàng JPOS",
  hint: "Theo dõi realtime toàn bộ đơn local, trạng thái thanh toán và đồng bộ.",
  search: "Mã đơn local hoặc JoyWorld",
  phone: "Số điện thoại",
  payment: "Thanh toán",
  sync: "Đồng bộ",
  employee: "Nhân viên",
  product: "Sản phẩm",
  all: "Tất cả",
  draft: "Nháp",
  paid: "Đã thanh toán",
  refunding: "Đang hoàn tiền",
  refunded: "Đã hoàn tiền",
  refundFailed: "Hoàn tiền lỗi",
  refundUnknown: "Chưa rõ kết quả hoàn",
  notSynced: "Chưa đồng bộ",
  pending: "Chờ đồng bộ",
  syncing: "Đang đồng bộ",
  syncFailed: "Đồng bộ lỗi",
  syncSuccess: "Đã đồng bộ",
  cancelled: "Đã hủy đồng bộ",
  newest: "Thời gian mới nhất",
  oldest: "Thời gian cũ nhất",
  amountHigh: "Tổng tiền cao nhất",
  amountLow: "Tổng tiền thấp nhất",
  orderCode: "Mã đơn",
  customer: "Khách hàng",
  total: "Tổng tiền",
  createdAt: "Thời gian tạo",
  noOrders: "Không có đơn hàng phù hợp.",
  loadMore: "Xem thêm đơn hàng",
  detail: "Chi tiết đơn hàng",
  localId: "Mã local",
  remoteId: "Mã JoyWorld",
  remoteUuid: "UUID JoyWorld",
  cashier: "Nhân viên",
  paymentMethod: "Phương thức thanh toán",
  products: "Sản phẩm trong đơn",
  quantity: "SL",
  unitPrice: "Đơn giá",
  invoice: "Hóa đơn MISA",
  noInvoice: "Chưa phát hành",
  syncHistory: "Đồng bộ",
  retryCount: "Số lần thử",
  lastError: "Lỗi gần nhất",
  cancelOrder: "Hủy đơn hàng",
  cancelReason: "Lý do hủy",
  cancelReasonPlaceholder: "Nhập lý do cụ thể để lưu audit",
  refundConfirmation:
    "Tôi xác nhận hoàn tiền theo đúng phương thức thanh toán ban đầu.",
  previewAmount: "Số tiền hoàn",
  previewMethod: "Phương thức hoàn",
  localOnly: "Đơn này chỉ hủy tại local và sẽ không được đồng bộ.",
  remoteRefund: "JoyWorld sẽ được hoàn tiền trước khi chốt hủy tại local.",
  cancellationBlocked: "Đơn hàng hiện không thể hủy.",
  cancelLoading: "Đang xử lý hủy đơn...",
  cancelSuccess: "Đã hủy đơn hàng",
  cancelSuccessDescription: "Trạng thái đơn hàng và audit đã được cập nhật.",
  cancelError: "Không thể hủy đơn hàng",
  retry: "Thử lại",
  close: "Đóng",
  cancelAudit: "Lịch sử hủy",
  sourceImported: "Đơn lịch sử JoyWorld",
  source: "Nguồn dữ liệu",
  status: "Trạng thái",
  refundOrderNumber: "Mã đơn hoàn JoyWorld",
  realtime: "Realtime",
  orderInformation: "Thông tin đơn hàng",
  device: "Thiết bị",
  memberCode: "Mã thành viên",
  paidAt: "Thời gian thanh toán",
  lineTotal: "Thành tiền",
  invoiceStatus: "Trạng thái hóa đơn",
  invoiceNumber: "Số hóa đơn",
  previewLoading: "Đang kiểm tra điều kiện hoàn tiền...",
  noPermission: "Bạn không có quyền hủy loại đơn hàng này.",
  reasonRequired: "Lý do hủy phải có ít nhất 3 ký tự.",
  confirmationRequired: "Cần xác nhận hoàn tiền trước khi tiếp tục.",
  operationId: "Mã thao tác",
  actionTime: "Thời gian thao tác",
  syncTime: "Thời gian ghi nhận",
  blockedSyncing: "Đơn đang đồng bộ; hãy chờ chuyển sang trạng thái khác.",
  blockedInvoice: "Đơn đang hoặc đã phát hành hóa đơn MISA.",
  blockedImported: "Đơn lịch sử JoyWorld chỉ được phép xem.",
  blockedRefunding: "Đơn đang được xử lý hoàn tiền.",
  blockedUnknown: "Kết quả hoàn tiền chưa rõ; cần đối soát thủ công.",
};

const zh: typeof vi = {
  tab: "订单",
  title: "JPOS 订单",
  hint: "实时查看本地订单、付款状态和同步状态。",
  search: "本地或 JoyWorld 订单号",
  phone: "手机号",
  payment: "付款",
  sync: "同步",
  employee: "员工",
  product: "商品",
  all: "全部",
  draft: "草稿",
  paid: "已付款",
  refunding: "退款中",
  refunded: "已退款",
  refundFailed: "退款失败",
  refundUnknown: "退款结果未知",
  notSynced: "未同步",
  pending: "等待同步",
  syncing: "同步中",
  syncFailed: "同步失败",
  syncSuccess: "已同步",
  cancelled: "同步已取消",
  newest: "最新时间",
  oldest: "最早时间",
  amountHigh: "金额从高到低",
  amountLow: "金额从低到高",
  orderCode: "订单号",
  customer: "客户",
  total: "总额",
  createdAt: "创建时间",
  noOrders: "没有符合条件的订单。",
  loadMore: "查看更多订单",
  detail: "订单详情",
  localId: "本地订单号",
  remoteId: "JoyWorld 订单号",
  remoteUuid: "JoyWorld UUID",
  cashier: "员工",
  paymentMethod: "支付方式",
  products: "订单商品",
  quantity: "数量",
  unitPrice: "单价",
  invoice: "MISA 发票",
  noInvoice: "尚未开具",
  syncHistory: "同步",
  retryCount: "重试次数",
  lastError: "最近错误",
  cancelOrder: "取消订单",
  cancelReason: "取消原因",
  cancelReasonPlaceholder: "请输入具体原因以记录审计",
  refundConfirmation: "我确认按原支付方式退款。",
  previewAmount: "退款金额",
  previewMethod: "退款方式",
  localOnly: "此订单仅在本地取消，且不会再同步。",
  remoteRefund: "先在 JoyWorld 退款，成功后再完成本地取消。",
  cancellationBlocked: "该订单当前无法取消。",
  cancelLoading: "正在取消订单...",
  cancelSuccess: "订单已取消",
  cancelSuccessDescription: "订单状态和审计记录已更新。",
  cancelError: "无法取消订单",
  retry: "重试",
  close: "关闭",
  cancelAudit: "取消记录",
  sourceImported: "JoyWorld 历史订单",
  source: "数据来源",
  status: "状态",
  refundOrderNumber: "JoyWorld 退款单号",
  realtime: "实时",
  orderInformation: "订单信息",
  device: "设备",
  memberCode: "会员号",
  paidAt: "付款时间",
  lineTotal: "小计",
  invoiceStatus: "发票状态",
  invoiceNumber: "发票号码",
  previewLoading: "正在检查退款条件...",
  noPermission: "您没有权限取消此类订单。",
  reasonRequired: "取消原因至少需要 3 个字符。",
  confirmationRequired: "继续前需要确认退款。",
  operationId: "操作编号",
  actionTime: "操作时间",
  syncTime: "记录时间",
  blockedSyncing: "订单正在同步，请等待状态变化。",
  blockedInvoice: "订单正在或已经开具 MISA 发票。",
  blockedImported: "JoyWorld 历史订单仅供查看。",
  blockedRefunding: "订单正在处理退款。",
  blockedUnknown: "退款结果未知，需要人工对账。",
};

export function usePosOrderCopy() {
  const { lang } = useTranslation();
  return lang === "zh" ? zh : vi;
}
