"use client";

import { useTranslation } from "@/lib/i18n";

const vi = {
  panelTitle: "Cấu hình in vé",
  panelHint: "Áp dụng cho từng vé vui chơi được in tại JPOS",
  version: "Phiên bản",
  reset: "Khôi phục mặc định",
  save: "Lưu cấu hình",
  saving: "Đang lưu...",
  saveLoading: "Đang lưu cấu hình vé...",
  saveSuccess: "Đã lưu cấu hình vé",
  saveSuccessDescription:
    "Cấu hình mới đang được gửi tức thì tới các máy JPOS của cửa hàng.",
  saveError: "Không thể lưu cấu hình vé",
  saveErrorDescription: "Vui lòng kiểm tra dữ liệu, kết nối mạng rồi thử lại.",
  retry: "Thử lại",
  preview: "Xem trước thực tế",
  previewHint:
    "Bản xem trước dùng đúng bố cục in vé tại JPOS và thay đổi ngay khi chỉnh cấu hình.",
  paperTitle: "Khổ và chiều dài vé",
  paperDescription: "Chọn vùng in thực tế và chiều dài cố định của từng vé.",
  ticketHeight: "Chiều dài vé",
  brandTitle: "Nhận diện trên vé",
  brandDescription:
    "Logo được chuyển sang thang xám và tăng tương phản khi in nhiệt.",
  uploadLogo: "Tải logo lên",
  replaceLogo: "Thay logo",
  removeLogo: "Xóa logo",
  logoAlt: "Logo cửa hàng",
  logoInvalid: "Logo không hợp lệ",
  logoInvalidDescription: "Chỉ chấp nhận ảnh PNG, JPG hoặc WEBP.",
  logoTooLarge: "Logo quá lớn",
  logoTooLargeDescription: "Vui lòng chọn ảnh nhỏ hơn 600 KB.",
  logoReadError: "Không thể đọc logo",
  logoReadErrorDescription: "Vui lòng chọn một tệp ảnh khác.",
  logoReady: "Đã cập nhật logo",
  logoReadyDescription: "Ảnh sẽ được chuyển sang đơn sắc khi in nhiệt.",
  storeName: "Tên cửa hàng",
  ticketTitle: "Tiêu đề vé",
  subtitle: "Dòng mô tả",
  logoWidth: "Chiều rộng logo",
  logoHeight: "Chiều cao tối đa",
  logoContrast: "Độ đậm logo",
  contentTitle: "Nội dung vé",
  contentDescription: "Điều chỉnh hướng dẫn và lời nhắn cuối vé.",
  instructions: "Hướng dẫn sử dụng",
  footer: "Lời nhắn cuối vé",
  typeTitle: "Chữ và mã QR",
  typeDescription: "Điều chỉnh kích thước để phù hợp với máy in nhiệt.",
  qrSize: "Kích thước mã QR",
  titleSize: "Cỡ chữ tiêu đề",
  productSize: "Cỡ chữ sản phẩm",
  bodySize: "Cỡ chữ nội dung",
  fontWeight: "Độ đậm tên sản phẩm",
  displayTitle: "Thông tin hiển thị",
  displayDescription: "Chọn các dữ liệu được in trên mỗi vé.",
  showLogo: "Hiển thị logo",
  showLogoHint: "Ẩn logo nhưng vẫn giữ tệp đã tải",
  showOrder: "Hiển thị mã đơn",
  showOrderHint: "In mã đơn hàng ở cuối vé",
  showIssued: "Hiển thị giờ phát hành",
  showIssuedHint: "In ngày và giờ tạo vé",
  showPrice: "Hiển thị giá vé",
  showPriceHint: "In giá bán dưới tên sản phẩm",
  showSequence: "Hiển thị số thứ tự vé",
  showSequenceHint: "Ví dụ Vé 2/7 đối với sản phẩm nhiều vé",
  autoPrint: "Tự động in sau thanh toán",
  autoPrintHint: "JPOS tự in đủ số vé ngay khi đơn hoàn tất",
};

const zh: typeof vi = {
  panelTitle: "票券打印设置",
  panelHint: "适用于 JPOS 打印的每张游乐票券",
  version: "版本",
  reset: "恢复默认",
  save: "保存设置",
  saving: "保存中...",
  saveLoading: "正在保存票券设置...",
  saveSuccess: "票券设置已保存",
  saveSuccessDescription: "新设置正实时发送到门店的 JPOS 设备。",
  saveError: "无法保存票券设置",
  saveErrorDescription: "请检查数据与网络连接后重试。",
  retry: "重试",
  preview: "实时预览",
  previewHint: "预览使用与 JPOS 完全相同的票券布局，并随设置即时变化。",
  paperTitle: "纸张与票券长度",
  paperDescription: "选择实际打印宽度和每张票券的固定长度。",
  ticketHeight: "票券长度",
  brandTitle: "票券品牌",
  brandDescription: "Logo 在热敏打印时会转换为灰度并增强对比度。",
  uploadLogo: "上传 Logo",
  replaceLogo: "更换 Logo",
  removeLogo: "删除 Logo",
  logoAlt: "门店 Logo",
  logoInvalid: "Logo 无效",
  logoInvalidDescription: "仅支持 PNG、JPG 或 WEBP 图片。",
  logoTooLarge: "Logo 过大",
  logoTooLargeDescription: "请选择小于 600 KB 的图片。",
  logoReadError: "无法读取 Logo",
  logoReadErrorDescription: "请选择其他图片文件。",
  logoReady: "Logo 已更新",
  logoReadyDescription: "图片在热敏打印时会转换为黑白。",
  storeName: "门店名称",
  ticketTitle: "票券标题",
  subtitle: "说明文字",
  logoWidth: "Logo 宽度",
  logoHeight: "最大高度",
  logoContrast: "Logo 对比度",
  contentTitle: "票券内容",
  contentDescription: "调整使用说明与票券底部留言。",
  instructions: "使用说明",
  footer: "底部留言",
  typeTitle: "文字与二维码",
  typeDescription: "调整尺寸以适配热敏打印机。",
  qrSize: "二维码尺寸",
  titleSize: "标题字号",
  productSize: "商品字号",
  bodySize: "正文字号",
  fontWeight: "商品字重",
  displayTitle: "显示内容",
  displayDescription: "选择每张票券上打印的数据。",
  showLogo: "显示 Logo",
  showLogoHint: "隐藏时仍保留已上传文件",
  showOrder: "显示订单号",
  showOrderHint: "在票券底部打印订单号",
  showIssued: "显示签发时间",
  showIssuedHint: "打印票券生成日期与时间",
  showPrice: "显示票价",
  showPriceHint: "在商品名称下打印售价",
  showSequence: "显示票券序号",
  showSequenceHint: "多票商品显示例如 2/7",
  autoPrint: "付款后自动打印",
  autoPrintHint: "订单完成后 JPOS 自动打印全部票券",
};

export function usePosTicketEditorCopy() {
  const { lang } = useTranslation();
  return { copy: lang === "zh" ? zh : vi, lang } as const;
}
