export const REVENUE_WORKBOOK_COPY = {
  vi: {
    revenueTitle: "BÁO CÁO DOANH THU",
    salesTitle: "BÁO CÁO CƠ CẤU BÁN HÀNG",
    invoiceTitle: "DỮ LIỆU CHUẨN BỊ XUẤT HÓA ĐƠN",
    selectedQuantity: "Số lượng sản phẩm đã chọn",
    selectedGroups: "Số nhóm đã chọn",
    summary: "Tổng quan",
    daily: "Doanh thu từng ngày",
    payments: "Cơ cấu thanh toán",
    groups: "Theo nhóm sản phẩm",
    products: "Chi tiết sản phẩm",
    store: "Cửa hàng",
    range: "Phạm vi",
    source: "Nguồn dữ liệu",
    generated: "Thời điểm xuất",
    totalRevenue: "Tổng doanh thu",
    cashRevenue: "Doanh thu tiền mặt",
    transferRevenue: "Doanh thu chuyển khoản",
    otherRevenue: "Doanh thu phương thức khác",
    totalOrders: "Tổng đơn hàng",
    averageOrder: "Giá trị đơn trung bình",
    date: "Ngày",
    paymentMethod: "Phương thức",
    category: "Phân loại",
    amount: "Số tiền",
    orderCount: "Số đơn",
    share: "Tỷ trọng",
    group: "Nhóm sản phẩm",
    product: "Sản phẩm",
    quantity: "Số lượng",
    revenue: "Doanh thu",
    averagePrice: "Giá bán trung bình",
    total: "TỔNG CỘNG",
    openApi: "OpenAPI",
    localPos: "POS local",
  },
  zh: {
    revenueTitle: "营收报表",
    salesTitle: "销售结构报表",
    invoiceTitle: "开票准备数据",
    selectedQuantity: "所选商品数量",
    selectedGroups: "所选分组数量",
    summary: "汇总",
    daily: "每日营收",
    payments: "支付结构",
    groups: "按商品组",
    products: "商品明细",
    store: "门店",
    range: "日期范围",
    source: "数据来源",
    generated: "导出时间",
    totalRevenue: "总营收",
    cashRevenue: "现金营收",
    transferRevenue: "转账营收",
    otherRevenue: "其他支付营收",
    totalOrders: "订单总数",
    averageOrder: "平均订单金额",
    date: "日期",
    paymentMethod: "支付方式",
    category: "分类",
    amount: "金额",
    orderCount: "订单数",
    share: "占比",
    group: "商品组",
    product: "商品",
    quantity: "数量",
    revenue: "营收",
    averagePrice: "平均售价",
    total: "合计",
    openApi: "OpenAPI",
    localPos: "本地 POS",
  },
} as const;

export type RevenueWorkbookCopy =
  | (typeof REVENUE_WORKBOOK_COPY)["vi"]
  | (typeof REVENUE_WORKBOOK_COPY)["zh"];
