export const externalCountDetailCopy = {
  vi: {
    title: "Chi tiết phiên kiểm đếm",
    close: "Đóng chi tiết",
    loadingError: "Không thể tải chi tiết phiên kiểm đếm",
    loadingErrorDescription: "Vui lòng kiểm tra kết nối hoặc thử lại sau.",
    retry: "Thử lại",
    sessionInfo: "Thông tin phiên",
    countResults: "Kết quả kiểm đếm",
    productLines: "Dòng hàng",
    issueLines: "Có chênh lệch",
    evidenceImages: "Ảnh minh chứng",
    warehouse: "Kho",
    location: "Quầy",
    checkpoint: "Thời điểm kiểm",
    businessDate: "Ngày nghiệp vụ",
    performedAt: "Thời gian thực hiện",
    operator: "Nhân viên",
    client: "Client",
    device: "Thiết bị",
    sessionCode: "Mã phiên",
    idempotency: "Mã chống trùng",
    notes: "Ghi chú phiên",
    noNotes: "Không có ghi chú",
    noItems: "Phiên kiểm đếm này chưa có dòng hàng.",
    product: "Sản phẩm",
    barcode: "Mã vạch",
    expected: "Dự kiến",
    counted: "Thực đếm",
    difference: "Chênh lệch",
    condition: "Tình trạng",
    reason: "Lý do chênh lệch",
    itemNote: "Ghi chú",
    noEvidence: "Không có ảnh minh chứng",
    openImage: "Mở ảnh minh chứng",
    imageViewer: "Xem ảnh minh chứng",
    imagePosition: "Ảnh",
    previousImage: "Ảnh trước",
    nextImage: "Ảnh tiếp theo",
    beforeScan: "Trước khi quét",
    beforeSubmit: "Trước khi nộp",
    statuses: {
      DRAFT: "Bản nháp",
      IN_PROGRESS: "Đang kiểm",
      SUBMITTED: "Đã nộp",
      COMPLETED: "Hoàn tất",
      DISCREPANCY_FOUND: "Có chênh lệch",
      VERIFIED: "Hợp lệ",
      RESOLVED: "Đã xử lý",
      CANCELLED: "Đã hủy",
    },
    conditions: {
      GOOD: "Tốt",
      DAMAGED: "Hư hỏng",
      EXPIRED: "Hết hạn",
      MISSING: "Thiếu hàng",
    },
  },
  zh: {
    title: "盘点会话详情",
    close: "关闭详情",
    loadingError: "无法加载盘点会话详情",
    loadingErrorDescription: "请检查网络连接或稍后重试。",
    retry: "重试",
    sessionInfo: "会话信息",
    countResults: "盘点结果",
    productLines: "商品行",
    issueLines: "存在差异",
    evidenceImages: "凭证图片",
    warehouse: "仓库",
    location: "柜台",
    checkpoint: "盘点节点",
    businessDate: "业务日期",
    performedAt: "执行时间",
    operator: "操作员",
    client: "客户端",
    device: "设备",
    sessionCode: "会话编号",
    idempotency: "幂等键",
    notes: "会话备注",
    noNotes: "无备注",
    noItems: "此盘点会话暂无商品行。",
    product: "商品",
    barcode: "条码",
    expected: "预期数量",
    counted: "实盘数量",
    difference: "差异",
    condition: "状态",
    reason: "差异原因",
    itemNote: "备注",
    noEvidence: "无凭证图片",
    openImage: "打开凭证图片",
    imageViewer: "查看凭证图片",
    imagePosition: "图片",
    previousImage: "上一张",
    nextImage: "下一张",
    beforeScan: "扫描前",
    beforeSubmit: "提交前",
    statuses: {
      DRAFT: "草稿",
      IN_PROGRESS: "盘点中",
      SUBMITTED: "已提交",
      COMPLETED: "已完成",
      DISCREPANCY_FOUND: "存在差异",
      VERIFIED: "有效",
      RESOLVED: "已处理",
      CANCELLED: "已取消",
    },
    conditions: {
      GOOD: "良好",
      DAMAGED: "损坏",
      EXPIRED: "已过期",
      MISSING: "缺失",
    },
  },
} as const;

export type ExternalCountDetailText =
  (typeof externalCountDetailCopy)[keyof typeof externalCountDetailCopy];
