export const externalCountPageCopy = {
  vi: {
    title: "Kiểm đếm external",
    configTitle: "Cấu hình bắt buộc kiểm đếm",
    enabled: "Bật kiểm đếm external",
    beforeScan: "Yêu cầu BEFORE_SCAN trước khi quét",
    beforeSubmit: "Yêu cầu BEFORE_SUBMIT trước khi nộp",
    save: "Lưu cấu hình",
    saving: "Đang lưu cấu hình...",
    saved: "Đã lưu cấu hình",
    saveError: "Không thể lưu cấu hình",
    saveDesc: "Luồng quét ngoài sẽ áp dụng cấu hình mới ngay.",
    saveErrorDesc: "Vui lòng kiểm tra quyền hoặc thử lại sau.",
    configLoadError: "Không thể tải cấu hình kiểm đếm",
    configLoadErrorDescription: "Vui lòng kiểm tra kết nối hoặc thử lại sau.",
    retry: "Thử lại",
    warehouse: "Kho",
    location: "Quầy",
    date: "Ngày",
    businessDate: "Ngày nghiệp vụ",
    performedAt: "Thời gian thực hiện",
    all: "Tất cả",
    searchLabel: "Tìm kiếm",
    search: "Tìm theo mã checkpoint, quầy, kho hoặc nhân viên...",
    emptyTitle: "Chưa có checkpoint kiểm đếm",
    emptyHint:
      "Hệ thống ngoài gửi POST /api/external/v1/count để tạo dữ liệu ở đây.",
    total: "Tổng checkpoint",
    verified: "Hợp lệ",
    issues: "Có chênh lệch",
    beforeScanLabel: "Trước khi quét",
    beforeSubmitLabel: "Trước khi nộp",
    operator: "Nhân viên",
    client: "Client",
    discrepancy: "Chênh lệch",
    idempotency: "Idempotency",
    viewDetails: "Xem chi tiết phiên kiểm đếm",
    statuses: {
      DRAFT: "Bản nháp",
      IN_PROGRESS: "Đang kiểm",
      SUBMITTED: "Đã nộp",
      COMPLETED: "Hoàn tất",
      DISCREPANCY_FOUND: "Có chênh lệch",
      VERIFIED: "Hợp lệ",
      RESOLVED: "Đã xử lý",
      CANCELLED: "Đã hủy",
    },
    noPermission:
      "Bạn không có quyền chỉnh cấu hình kiểm đếm external.",
  },
  zh: {
    title: "外部盘点",
    configTitle: "外部盘点要求",
    enabled: "启用外部盘点",
    beforeScan: "扫描前需要 BEFORE_SCAN",
    beforeSubmit: "提交前需要 BEFORE_SUBMIT",
    save: "保存配置",
    saving: "正在保存配置...",
    saved: "配置已保存",
    saveError: "无法保存配置",
    saveDesc: "外部扫描流程会立即使用新配置。",
    saveErrorDesc: "请检查权限或稍后重试。",
    configLoadError: "无法加载盘点配置",
    configLoadErrorDescription: "请检查网络连接或稍后重试。",
    retry: "重试",
    warehouse: "仓库",
    location: "柜台",
    date: "日期",
    businessDate: "业务日期",
    performedAt: "执行时间",
    all: "全部",
    searchLabel: "搜索",
    search: "按检查点、柜台、仓库或员工搜索...",
    emptyTitle: "暂无盘点检查点",
    emptyHint: "外部系统通过 POST /api/external/v1/count 提交数据。",
    total: "检查点总数",
    verified: "有效",
    issues: "有差异",
    beforeScanLabel: "扫描前",
    beforeSubmitLabel: "提交前",
    operator: "操作员",
    client: "客户端",
    discrepancy: "差异",
    idempotency: "幂等键",
    viewDetails: "查看盘点会话详情",
    statuses: {
      DRAFT: "草稿",
      IN_PROGRESS: "盘点中",
      SUBMITTED: "已提交",
      COMPLETED: "已完成",
      DISCREPANCY_FOUND: "存在差异",
      VERIFIED: "有效",
      RESOLVED: "已处理",
      CANCELLED: "已取消",
    },
    noPermission: "您没有权限修改外部盘点配置。",
  },
} as const;

export type ExternalCountPageText =
  (typeof externalCountPageCopy)[keyof typeof externalCountPageCopy];
